name: WorldResetter
main: com.worldresetter.WorldResetter
api-version: "1.21"
version: 1.3.0
author: UstaGodzilla (Github:MrGodzilla38)

permissions:
  worldresetter.admin:
    description: Allows managing WorldResetter
    default: op
